
export const ESCROW_TEMPLATE = `
;; Title: Safe USDCx Escrow
;; Generated by: USDCx Integration Studio
;; Safety: Audited Patterns Only

(use-trait usdc-trait '{{USDC_TRAIT_CONTRACT}}.usdc-trait)

;; Constants
(define-constant ERR-NOT-AUTHORIZED (err u100))
(define-constant ERR-ALREADY-LOCKED (err u101))
(define-constant ERR-INVALID-EXPIRY (err u102))
(define-constant ERR-NOT-EXPIRED (err u103))

;; Data Vars
(define-data-var beneficiary principal '{{BENEFICIARY}})
(define-data-var arbiter principal '{{ARBITER}})
(define-data-var unlock-height uint u{{UNLOCK_HEIGHT}})
(define-data-var is-locked bool false)

;; Read-only functions
(define-read-only (get-details)
    (ok {
        beneficiary: (var-get beneficiary),
        arbiter: (var-get arbiter),
        unlock-height: (var-get unlock-height),
        is-locked: (var-get is-locked)
    })
)

;; Public functions

;; Lock USDCx into the contract
(define-public (lock-funds (amount uint) (usdc-contract <usdc-trait>))
    (begin
        (asserts! (not (var-get is-locked)) ERR-ALREADY-LOCKED)
        (asserts! (> (var-get unlock-height) block-height) ERR-INVALID-EXPIRY)
        
        ;; Transfer USDCx from sender to this contract
        (try! (contract-call? usdc-contract transfer amount tx-sender (as-contract tx-sender) none))
        
        (var-set is-locked true)
        (ok true)
    )
)

;; Release funds to beneficiary (by Arbiter)
(define-public (release-funds (usdc-contract <usdc-trait>))
    (let (
        (amount (unwrap-panic (contract-call? usdc-contract get-balance (as-contract tx-sender))))
    )
    (begin
        (asserts! (is-eq tx-sender (var-get arbiter)) ERR-NOT-AUTHORIZED)
        (asserts! (var-get is-locked) ERR-NOT-AUTHORIZED)
        
        ;; Transfer all funds to beneficiary
        (as-contract (contract-call? usdc-contract transfer amount tx-sender (var-get beneficiary) none))
    ))
)

;; Refund to depositor if expired (Timelock)
(define-public (refund (usdc-contract <usdc-trait>))
    (let (
        (amount (unwrap-panic (contract-call? usdc-contract get-balance (as-contract tx-sender))))
    )
    (begin
        (asserts! (>= block-height (var-get unlock-height)) ERR-NOT-EXPIRED)
        (asserts! (var-get is-locked) ERR-NOT-AUTHORIZED)
        
        ;; In a real scenario, we might want to track the original sender, 
        ;; but for this simple template we allow the arbiter to trigger refund or 
        ;; we could hardcode a 'depositor' variable. 
        ;; For safety here, we will refund to the Arbiter (assuming they are the depositor/admin role)
        ;; or we could add a 'depositor' field.
        
        (as-contract (contract-call? usdc-contract transfer amount tx-sender (var-get arbiter) none))
    ))
)
`;
