
export const ESCROW_TEMPLATE = `
;; Title: Safe USDCx Escrow
;; Generated by: USDCx Integration Studio
;; Safety: Audited Patterns Only
;; Description: Holds USDCx in escrow until release conditions are met.

;; Traits
;; Implements SIP-010 Fungible Token standard for USDCx
(use-trait sip-010-trait '{{USDC_TRAIT_CONTRACT}}.sip-010-trait)

;; Implements xReserve trait for cross-chain capabilities (mint/burn access)
;; Included for advanced bridging integrations
(use-trait xreserve-trait '{{USDC_TRAIT_CONTRACT}}.xreserve-trait)

;; Constants
(define-constant ERR-NOT-AUTHORIZED (err u100))
(define-constant ERR-ALREADY-LOCKED (err u101))
(define-constant ERR-INVALID-EXPIRY (err u102))
(define-constant ERR-NOT-EXPIRED (err u103))
(define-constant ERR-INVALID-AMOUNT (err u104))

;; Data Vars
(define-data-var beneficiary principal '{{BENEFICIARY}})
(define-data-var arbiter principal '{{ARBITER}})
(define-data-var unlock-height uint u{{UNLOCK_HEIGHT}})
(define-data-var is-locked bool false)

;; Read-only functions
(define-read-only (get-details)
    (ok {
        beneficiary: (var-get beneficiary),
        arbiter: (var-get arbiter),
        unlock-height: (var-get unlock-height),
        is-locked: (var-get is-locked)
    })
)

;; Public functions

;; Lock USDCx into the contract
;; @param amount: Amount of USDCx to lock
;; @param usdc-contract: The USDCx contract principal implementing sip-010-trait
(define-public (lock-funds (amount uint) (usdc-contract <sip-010-trait>))
    (begin
        (asserts! (not (var-get is-locked)) ERR-ALREADY-LOCKED)
        (asserts! (> (var-get unlock-height) block-height) ERR-INVALID-EXPIRY)
        (asserts! (> amount u0) ERR-INVALID-AMOUNT)
        
        ;; Perform SIP-010 Transfer
        ;; Moves USDCx from the sender to this contract
        (try! (contract-call? usdc-contract transfer amount tx-sender (as-contract tx-sender) none))
        
        (var-set is-locked true)
        (ok true)
    )
)

;; Release funds to beneficiary (by Arbiter)
;; @param usdc-contract: The USDCx contract principal implementing sip-010-trait
(define-public (release-funds (usdc-contract <sip-010-trait>))
    (let (
        (amount (unwrap-panic (contract-call? usdc-contract get-balance (as-contract tx-sender))))
    )
    (begin
        ;; ARBITER CHECK: Only the designated arbiter can release funds
        (asserts! (is-eq tx-sender (var-get arbiter)) ERR-NOT-AUTHORIZED)
        (asserts! (var-get is-locked) ERR-NOT-AUTHORIZED)
        
        ;; Perform SIP-010 Transfer to Beneficiary
        (as-contract (contract-call? usdc-contract transfer amount tx-sender (var-get beneficiary) none))
    ))
)

;; Refund to depositor if expired (Timelock)
;; @param usdc-contract: The USDCx contract principal implementing sip-010-trait
(define-public (refund (usdc-contract <sip-010-trait>))
    (let (
        (amount (unwrap-panic (contract-call? usdc-contract get-balance (as-contract tx-sender))))
    )
    (begin
        ;; TIMELOCK CHECK: Ensure current block height >= unlock height
        (asserts! (>= block-height (var-get unlock-height)) ERR-NOT-EXPIRED)
        (asserts! (var-get is-locked) ERR-NOT-AUTHORIZED)
        
        ;; Refund to Arbiter (Acting as Depositor/Admin in this simple model)
        (as-contract (contract-call? usdc-contract transfer amount tx-sender (var-get arbiter) none))
    ))
)

;; Advanced: Burn funds (Bridge-out scenario)
;; @param amount: Amount to burn
;; @param xreserve-contract: The USDCx contract implementing xreserve-trait
(define-public (bridge-out (amount uint) (xreserve-contract <xreserve-trait>))
    (begin
        ;; ARBITER CHECK: Only arbiter can initiate bridge-out
        (asserts! (is-eq tx-sender (var-get arbiter)) ERR-NOT-AUTHORIZED)
        (asserts! (var-get is-locked) ERR-NOT-AUTHORIZED)
        
        ;; Perform xReserve Burn
        ;; This simulates a bridge-out event where funds are removed from Stacks circulation
        (as-contract (try! (contract-call? xreserve-contract burn amount (var-get beneficiary))))
        
        (ok true)
    )
)
`;
